name: Pull request

on:
  pull_request:
    branches:
      - main

run-name: ${{ github.action }} has opened/updated a pull request

jobs:
    terraform-validate-and-plan:
      uses: ./.github/workflows/tf-validate-plan.yml
      with:
        apply-config: false