name: Merge to main

on:
    push:
        branches:
            - main

run-name: ${{ github.actor }} has merged a pull request to main

jobs:
    terraform-validate-and-plan:
        uses: ./.github/workflows/tf-validate-plan.yml
        with:
            apply-config: true